/******************************************************************************/
/*** Generated by IBExpert 2021.10.20.1 29.10.2021 13:11:40 ***/
/******************************************************************************/
SET SQL DIALECT 3;
SET NAMES WIN1251;
CREATE DATABASE 'C:\Dbase\TRADE.FDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET WIN1251 COLLATION WIN1251;
/******************************************************************************/
/*** Tables ***/
/******************************************************************************/
CREATE TABLE CUSTOMERS (
CNUM INTEGER NOT NULL,
CNAME VARCHAR(20),
CITY VARCHAR(20),
RATING INTEGER,
SNUM INTEGER
);
CREATE TABLE ORDERS (
ONUM INTEGER NOT NULL,
AMT NUMERIC(15,2),
ODATE DATE,
CNUM INTEGER,
SNUM INTEGER
);
CREATE TABLE SALESPEOPLE (
SNUM INTEGER NOT NULL,
SNAME VARCHAR(20),
CITY VARCHAR(20),
COMM DECIMAL(5,2)
);
/******************************************************************************/
/*** Primary keys ***/
/******************************************************************************/
ALTER TABLE CUSTOMERS ADD CONSTRAINT PK_CUSTOMERS PRIMARY KEY (CNUM);
ALTER TABLE ORDERS ADD CONSTRAINT PK_ORDERS PRIMARY KEY (ONUM);
ALTER TABLE SALESPEOPLE ADD CONSTRAINT PK_SALESPEOPLE PRIMARY KEY
(SNUM);
/******************************************************************************/
/*** Descriptions ***/
/******************************************************************************/

DESCRIBE TABLE CUSTOMERS
'Заказчики';
DESCRIBE TABLE ORDERS
'Заказы';
DESCRIBE TABLE SALESPEOPLE
'Продавцы';

INSERT SALESPEOPLE(SNUM, SNAME, CITY, COMM) 
VALUES (1, 'Иванов', 'Рязань', 0,11);
